# Generated by Django 5.0.7 on 2024-09-26 09:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("parent", "0002_initial"),
        ("student", "0001_initial"),
        ("teacher", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="class_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="teacher.class"
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="parent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="parent.parent",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
